import { AiFillStar } from "react-icons/ai";

const Productdata = [
  {
    img: "https://tse4.mm.bing.net/th?id=OIP.zlZI0kLKy12G1tUBd2P-ugHaHa&pid=Api&P=0&h=180",
    title: "Classic Leash",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs 540",
    newPrice: "200",
    company: "Blitz",
    color: "pink",
    category: "Leashes",
  },
  {
    img: "https://tse4.mm.bing.net/th?id=OIP.qfeFdRdK_h1gh1vBq1u2RAHaHa&pid=Api&P=0&h=180",
    title: "Heavy Duty Retractable Leash",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs 1400",
    newPrice: "800",
    company: "Rage",
    color: "black",
    category: "Leashes",
  },

  {
    img: "https://tse4.mm.bing.net/th?id=OIP.sstanDE3IMqPcW8KOqDGxAHaKn&pid=Api&P=0&h=180",
    title: "Meow Mix Cat Food",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs 600",
    newPrice: "300",
    company: "Meow Mix",
    color:"yellow",
    category: "Pet Food",
  },
  {
    img: "https://tse2.mm.bing.net/th?id=OIP.hYWtZ5l2PyRGDnz46VGf8AHaHa&pid=Api&P=0&h=180",
    title: "Pedigree Dog Food",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs 700",
    newPrice: "200",
    company: "Pedigree",
    color: "yellow",
    category: "Pet Food",
  },
  {
    img: "https://tse2.mm.bing.net/th?id=OIP.5rUPu_6i8y4Hvfpqhm_rCQHaHa&pid=Api&P=0&h=180",
    title: "Pure Fun Bird Food",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs 400",
    newPrice: "100",
    company: "Pure Fun",
    color: "purple",
    category: "Pet Food",
  },
  {
    img: "https://tse2.mm.bing.net/th?id=OIP.smAJQzyUsI46G0oTA8kqKAHaHa&pid=Api&P=0&h=180",
    title: "Dog Chewer",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs 300",
    newPrice: "50",
    company: "Eimeli",
    color: "white",
    category: "Pet Toys",
  },

  {
    img: "https://tse3.mm.bing.net/th?id=OIP.h8G85igZE5wti7QOBri1ngHaFi&pid=Api&P=0&h=180",
    title: "Cat Scratcher Toy",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs 400",
    newPrice: "300",
    company: "Blitz",
    color: "brown",
    category: "Pet Toys",
  },

  {
    img: "https://tse2.mm.bing.net/th?id=OIP.9B4uygtLaUqfXb8QVYSnnAHaHI&pid=Api&P=0&h=180",
    title: "Bellpull Bird Toy",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs 100",
    newPrice: "80",
    company: "Bonkers",
    color: "yellow",
    category: "Pet Toys",
  },

  {
    img: "https://tse4.mm.bing.net/th?id=OIP.zSJOn0lbxBmAyXbYcYVmEQHaHa&pid=Api&P=0&h=180",
    title: "Waterproof Dog Vest",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs 1500",
    newPrice: "200",
    company: "Blitz",
    color: "black",
    category: "Pet Clothes",
  },

  {
    img: "https://tse2.mm.bing.net/th?id=OIP.sckNw_R6HjkOWpMpx4RWbQHaHa&pid=Api&P=0&h=180",
    title: "Cat Jacket",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs 1600",
    newPrice: "500",
    company: "Bonkers",
    color: "blue",
    category: "Pet Clothes",
  },
  {
    img: "https://tse2.mm.bing.net/th?id=OIP.dcn1DFZ_A8nJxtDldZ4ZfgHaHa&pid=Api&P=0&h=180",
    title: "Parrot Tux",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs 2200",
    newPrice: "2000",
    company: "Bonkers",
    color: "black",
    category: "Pet Clothes",
  },
  {
    img: "https://ipetcompanion.net/wp-content/uploads/2019/11/4.-Yizhi-Miaow-Escape-Proof-Kitten-Harness-with-Leash-1024x1024.jpg",
    title: " Cat Harness And Leash",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs 700",
    newPrice: "500",
    company: "Rage",
    color: "black",
    category: "Leashes",
  },
  {
    img: "https://tse2.mm.bing.net/th?id=OIP.xr_zGdKzQOL3dlaK1dy84wHaHa&pid=Api&P=0&h=180",
    title: " Leather Dog Leash",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs 500",
    newPrice: "100",
    company: "Bonkers",
    color: "yellow",
    category: "Leashes",
  },
  {
    img: "https://tse3.mm.bing.net/th?id=OIP.-bQLD7wkVf51ASh-X-CGrgHaHa&pid=Api&P=0&h=180",
    title: "Birds Diet Food",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs 1000",
    newPrice: "500",
    company: "Hartz",
    color: "yellow",
    category: "Pet Food",
  },
  {
    img: "https://tse2.mm.bing.net/th?id=OIP.3FJybk3sIizIpL4j4VdpzAHaHa&pid=Api&P=0&h=180",
    title: "Dry Cat Food",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs 1000",
    newPrice: "500",
    company: "Hartz",
    color: "pink",
    category: "Pet Food",
  },
  {
    img: "https://tse4.mm.bing.net/th?id=OIP.bcF1eeJCThuk_F_PQSvqXwHaHa&pid=Api&P=0&h=180",
    title: "Cat Fishing Rod",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs 1000",
    newPrice: "500",
    company: "Hartz",
    color: "blue",
    category: "Pet Toys",
  },
  
];

export default Productdata;